version: "3.9"
services:
  t1-openschool-user-service-postgres:
    image: postgres:16
    container_name: t1_openschool_user_service_postgres
    environment:
      POSTGRES_DB: "user_service"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - t1-openschool-network

  t1-openschool-user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: t1_openschool_user_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://t1-openschool-user-service-postgres:5432/user_service
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - t1-openschool-user-service-postgres
    networks:
      - t1-openschool-network

networks:
  t1-openschool-network:
